ES6: Modules, Export and Import implementation
Nahid1911/Re-create_awesome_book_app pull request #1
Opened 2023-05-01 22:53 UTC by Nahid1911

**### Requirements:**

1. Setup your project with git, NPM, Index.js, index.css, index.html, and create modules directory.
2. Re-created Awesome books app following ES6 syntax, use different modules, imported modules into index.js file,
3. Used arrow function for all case.
4. Display current date using "Luxon" library.

***for details requirements please visit the [link](https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md)***

2023-05-01 23:05 UTC, codecaiine commented
hi @Nahid1911  I sent you a message on slack

2023-05-01 23:37 UTC, codecaiine requested changes
Hi @Nahid1911 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Adding and removing work as expected ✔️ 
- Luxon library is well implemented ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 23:37 UTC, codecaiine commented on modules/luxon.js
> +// eslint-disable-next-line max-classes-per-file
- [ ] I noticed that you disabled a lot  **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2023-05-01 23:37 UTC, codecaiine commented on modules/functions.js
> +function displayBooks(book, index) {
- [ ] I would like to recommend you use the **arrow functions** instead of **regular functions** as required for this project. Please fix it in order to make your project follow all the requirements 👍

2023-05-01 23:37 UTC, codecaiine commented on index.js
> +/* eslint-disable linebreak-style */
- [ ] I noticed that you disabled **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2023-05-02 07:23 UTC, Nahid1911 commented on modules/luxon.js
> +// eslint-disable-next-line max-classes-per-file
Thank you for your comments. This is a third party code, and It includes thousands of linters errors i have tried to fix those and spent more than 4 hours on that but i found that correction of one make many others incorrect. So, leaving it as it is, as it is not my code.

2023-05-02 07:23 UTC, Nahid1911 commented on modules/functions.js
> +function displayBooks(book, index) {
Fixed

2023-05-02 07:23 UTC, Nahid1911 commented on index.js
> +/* eslint-disable linebreak-style */
Fixed

2023-05-02 07:36 UTC, Shedrack-Sunday approved these changes
Hi @Nahid1911 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Cool structure 👍 
- Nice use of import/eport 👍
- Nice use of javascript library 👍  

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-02 07:36 UTC, Shedrack-Sunday approved these changes
Hi @Nahid1911 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Cool structure 👍 
- Nice use of import/eport 👍
- Nice use of javascript library 👍  

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-02 07:39 UTC, merged